### ISSUE TITLE
base64 string

### ISSUE THREAD

**Issue by ghost** [its-pablo/windows94#1]
i'd recommend using a base64 string instead of a zip file so you can save on library space

just a suggestion, do what you want

**Comment by stretch07** [comment]
great idea! I'll work on this soon.

**Comment by raymonable** [comment]
hi it's me again from the future where im significantly smarter

DO NOT DO THIS

just setup your repository in a way that lets it install every file by fetching them 
that way you won't need to import jszip just to install the files lol

**Comment by raymonable** [comment]
btw making this as a base64 string would likely increase it's size by 15 - 45% so i was really wrong about the statement of "saving library space" lol

**Comment by stretch07** [comment]
hm ur right

**Comment by stretch07** [comment]
I'll work on this. In the meantime, I've sent a message to ziad to see if all this is ok with him (he's the creator of win94)

**Comment by raymonable** [comment]
ok cool
